#!/usr/bin/env bash
# Turn Material Symbols downloads into the symbolic icons Atlas installs.
#
# Google's exports are already close to what GTK wants — a single filled path,
# no strokes — but they need three things doing to them:
#
#   * Renaming. Icon lookup goes current theme -> parents -> hicolor last, and
#     Atlas installs into hicolor, so an icon called "battery-symbolic" would
#     lose to the system theme's own and never appear. Everything is prefixed
#     "atlas-" so it cannot collide. The "-symbolic" suffix is what tells GTK the
#     icon may be recoloured.
#   * A black fill. The exports carry whatever colour the website previewed
#     with, often a pale grey. GTK overrides it when recolouring, but anything
#     else that renders the file — a thumbnailer, a browser — would show pale
#     grey on white.
#   * A nominal 16px size, which is what these are drawn at in the sidebar. The
#     viewBox is left alone; it defines the coordinate system, not the size.
#
# Run from the repository root:  scripts/import-icons.sh
#
# Source files are read from assets/icons/<name>.svg and left in place; the
# results are written alongside as atlas-<name>-symbolic.svg.
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")/.."
dir=assets/icons

# <downloaded name>:<installed name>
map=(
    cpu:cpu
    memory:memory
    disk:disk
    gpu:gpu
    ethernet:network
    wifi:wifi
    battery:battery
    apps:apps
    services:services
    settings:settings
    update:update
    trash:trash
    reset:reset
    warning:warning
    power-saving:energy
)

fail=0
for pair in "${map[@]}"; do
    src="$dir/${pair%%:*}.svg"
    dst="$dir/atlas-${pair##*:}-symbolic.svg"

    if [ ! -f "$src" ]; then
        echo "  missing: $src"
        continue
    fi

    # A stroke would not recolour: GTK forces the fill on rect, circle and path,
    # so stroked artwork keeps its own colour and turns invisible in dark mode.
    # Refuse rather than ship something that looks fine until the theme changes.
    if grep -q 'stroke' "$src"; then
        echo "  REFUSED: $src contains a stroke — convert it to outlines first"
        fail=1
        continue
    fi
    # A fill="none" bounding box becomes a solid square once GTK forces the fill.
    if grep -q 'fill="none"' "$src"; then
        echo "  REFUSED: $src has a fill=\"none\" element — remove it first"
        fail=1
        continue
    fi

    python3 - "$src" "$dst" <<'PY'
import re, sys
src, dst = sys.argv[1], sys.argv[2]
svg = open(src).read().strip()
svg = re.sub(r'\s(width|height)="[^"]*"', '', svg, count=2)
svg = re.sub(r'\sfill="[^"]*"', '', svg, count=1)
svg = svg.replace('<svg ', '<svg width="16" height="16" fill="#000000" ', 1)
header = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!-- Material Symbols (Outlined, weight 400, grade 0, optical size 20),\n'
    '     Apache License 2.0 — see NOTICE. Filled paths only: GTK recolours a\n'
    '     symbolic icon by forcing the fill, so a stroke would not follow the\n'
    '     theme. Generated by scripts/import-icons.sh; edit the source file\n'
    '     beside this one rather than this. -->\n'
)
open(dst, 'w').write(header + svg + '\n')
PY
    echo "  $(basename "$src")  ->  $(basename "$dst")"
done

exit $fail
